apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  name: prometheus-stack-grafana
  namespace: monitoring
spec:
  ports:
  - port: 3000
    protocol: TCP
    name: grafana-loadbalancer
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: prometheus-stack
    app.kubernetes.io/name: grafana
  type: LoadBalancer
